// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNsL7kyI9vBZo1Q58dvBqn8T_mtNLuxrc',
    appId: '1:655806781786:web:abd95c8857df1a3bc97b63',
    messagingSenderId: '655806781786',
    projectId: 'qr-code-app-pro-d3dbe',
    authDomain: 'qr-code-app-pro-d3dbe.firebaseapp.com',
    storageBucket: 'qr-code-app-pro-d3dbe.firebasestorage.app',
    measurementId: 'G-200S5JS5EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyopwaGhppXZhxzKVAtB1USFY-pKR8T0',
    appId: '1:655806781786:android:c56c93ce798a73adc97b63',
    messagingSenderId: '655806781786',
    projectId: 'qr-code-app-pro-d3dbe',
    storageBucket: 'qr-code-app-pro-d3dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBlAW8QBDsBrCT4iBXqfxSma2CEUD5Zro',
    appId: '1:655806781786:ios:0bcfcf5e0e2b0cd4c97b63',
    messagingSenderId: '655806781786',
    projectId: 'qr-code-app-pro-d3dbe',
    storageBucket: 'qr-code-app-pro-d3dbe.firebasestorage.app',
    iosBundleId: 'com.example.qrOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBlAW8QBDsBrCT4iBXqfxSma2CEUD5Zro',
    appId: '1:655806781786:ios:0bcfcf5e0e2b0cd4c97b63',
    messagingSenderId: '655806781786',
    projectId: 'qr-code-app-pro-d3dbe',
    storageBucket: 'qr-code-app-pro-d3dbe.firebasestorage.app',
    iosBundleId: 'com.example.qrOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNsL7kyI9vBZo1Q58dvBqn8T_mtNLuxrc',
    appId: '1:655806781786:web:90be303d3a4dde97c97b63',
    messagingSenderId: '655806781786',
    projectId: 'qr-code-app-pro-d3dbe',
    authDomain: 'qr-code-app-pro-d3dbe.firebaseapp.com',
    storageBucket: 'qr-code-app-pro-d3dbe.firebasestorage.app',
    measurementId: 'G-WEXTCG3B4B',
  );
}
